#ifndef SCHEDCLIENT_GLOBAL_H
#define SCHEDCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCHEDCLIENT_LIBRARY)
#  define SCHEDCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
//#  define SCHEDCLIENTSHARED_EXPORT Q_DECL_IMPORT
#  define SCHEDCLIENTSHARED_EXPORT
#endif

#endif // SCHEDCLIENT_GLOBAL_H
